name: Upload to Cloudflare Pages
on:
  push:
    branches:
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Move fonts to shared directory
        run: |
          mkdir -p static/fonts/; mkdir r2dist/
          if [ -d "static/dashboard/fonts" ]; then
            cp static/dashboard/fonts/element-icons.*.woff static/fonts/element-icons.woff
            cp static/dashboard/fonts/element-icons.*.ttf static/fonts/element-icons.ttf
          fi
          mv robots.txt static/ r2dist/
          echo "${{ secrets.CF_CONFIG }}" > r2dist/_redirects

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: r2dist/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          wranglerVersion: '3'
